my_dbt_project:
  outputs:
    dev:
      dataset: raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-central1
      method: oauth
      priority: interactive
      project: data-engineer-portfolio-milka
      threads: 1
      type: bigquery
  target: dev