FROM apache/airflow:3.1.3

USER airflow

# Copy only dbt requirements
COPY requirements-dbt.txt /tmp/requirements-dbt.txt

# Install dbt (BigQuery adapter)
RUN pip install --no-cache-dir -r /tmp/requirements-dbt.txt